menu:
   annonces:
     maintenance: "§c[§fALERT§c] §eThe Server Is Going into Maintenance! !"
back:
   message:
     teleportation: "§aTeleportation Confirmed !"
     not-death: "§c You isn't dead !"

spawn:
  world: world
  x: 0
  y: 33.0
  z: 0
  yaw: 0
  pitch: 0

###########################
#                         #
#      HOME PLAYERS       #
#                         #
###########################