name: FunDeads
version: 1.0.1
main: fr.fundeads.main.Main
author: FundeadsDev
commands:
  broadcast:
    description: Send Message to all Server !
    permission: fundeads.bc
  bc:
    permission: fundeads.bc
  menu:
    description: Menu [Admin | Joueurs]
    permission: fundeads.menu
  spawn:
    description: Goto to Spawn
  setspawn:
    description: Set Spawn of this Server
    permission: fundeads.setspawn
  heure:
    description: Show The Time Actually
  gm:
    description: Gamemode <0|1|2|3>
    permission: fundeads.gamemode
  food:
    description: Food Max
    permission: fundeads.food
  f:
    description: Food Max
    permission: fundeads.food
  heal:
    description: Heal Max
    permission: fundeads.heal
  h:
    description: Heal Max
    permission: fundeads.heal
  back:
    description: Goto to Death Emplacement !
  home:
    description: Goto a Home !
    permission: fundeads.home
  sethome:
    description: Set an Home !
    permission: fundeads.sethome
  delhome:
    description: Delete a Home !
    permission: fundeads.delhome
  vanish:
    description: Vanished You !
    permission: fundeads.vanish
  freeze:
    description: Freeze An Player !
    permission: fundeads.freeze
  day:
    description: Set Day In The World !
    permission: fundeads.day
  invsee:
    description: Open Inventory of a player.
    permission: fundeads.invsee